### ISSUE TITLE
change in results

### ISSUE THREAD

**Issue by MangeurDeCowan** [oduvan/checkio-mission-caps-lock#5]
The description page shows:
caps_lock("Madder than Mad Brian of Madcastle") == "MDDER THn MD BRIn of MDCstle"

My code had previously worked; however, when I recently tried running the code again to publish my solution, I got this error:
Right result:"MDDER THn MD bRIn of MDCstle"

The 'B' in Brian now shows that it should be a 'b'. I also tried pasting others published solutions, and they don't appear to work either. I'm not sure if I'm doing something wrong.

**Comment by AndroidBaaaby** [comment]
I'm in the same situation. I thought that the case testing went wrong.
